
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class ChooseAnOption extends javax.swing.JFrame {

    /**
     * Creates new form ChooseAnOption
     */
    public ChooseAnOption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMeanWindow = new javax.swing.JButton();
        btnModeWindow = new javax.swing.JButton();
        btnMeadianWindow = new javax.swing.JButton();
        btnWeighedWindow = new javax.swing.JButton();
        btnMeanDevWindow = new javax.swing.JButton();
        btnVarianceWindow = new javax.swing.JButton();
        btnRangeWindow = new javax.swing.JButton();
        btnStandardDevWindow = new javax.swing.JButton();
        btnQuartileDevWindow = new javax.swing.JButton();
        btnCoeffiencientOfVarWindow = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMeanWindow.setBackground(new java.awt.Color(0, 0, 204));
        btnMeanWindow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMeanWindow.setForeground(new java.awt.Color(255, 255, 255));
        btnMeanWindow.setText("MEAN");
        btnMeanWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMeanWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeanWindowActionPerformed(evt);
            }
        });
        getContentPane().add(btnMeanWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 200, 50));

        btnModeWindow.setBackground(new java.awt.Color(0, 0, 102));
        btnModeWindow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnModeWindow.setForeground(new java.awt.Color(252, 250, 250));
        btnModeWindow.setText("MODE");
        btnModeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModeWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModeWindowActionPerformed(evt);
            }
        });
        getContentPane().add(btnModeWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 190, 60));

        btnMeadianWindow.setBackground(new java.awt.Color(0, 0, 102));
        btnMeadianWindow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMeadianWindow.setForeground(new java.awt.Color(252, 250, 250));
        btnMeadianWindow.setText("MEDIAN");
        btnMeadianWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMeadianWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeadianWindowActionPerformed(evt);
            }
        });
        getContentPane().add(btnMeadianWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 190, 60));

        btnWeighedWindow.setBackground(new java.awt.Color(0, 0, 102));
        btnWeighedWindow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnWeighedWindow.setForeground(new java.awt.Color(252, 250, 250));
        btnWeighedWindow.setText("WEIGHED MEAN");
        btnWeighedWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWeighedWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWeighedWindowActionPerformed(evt);
            }
        });
        getContentPane().add(btnWeighedWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 210, 60));

        btnMeanDevWindow.setBackground(new java.awt.Color(0, 0, 102));
        btnMeanDevWindow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMeanDevWindow.setForeground(new java.awt.Color(252, 250, 250));
        btnMeanDevWindow.setText("MEAN DEVIATION ");
        btnMeanDevWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMeanDevWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeanDevWindowActionPerformed(evt);
            }
        });
        getContentPane().add(btnMeanDevWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 210, 50));

        btnVarianceWindow.setBackground(new java.awt.Color(0, 0, 102));
        btnVarianceWindow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVarianceWindow.setForeground(new java.awt.Color(252, 250, 250));
        btnVarianceWindow.setText("VARIANCE");
        btnVarianceWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVarianceWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVarianceWindowActionPerformed(evt);
            }
        });
        getContentPane().add(btnVarianceWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 210, 60));

        btnRangeWindow.setBackground(new java.awt.Color(0, 0, 102));
        btnRangeWindow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRangeWindow.setForeground(new java.awt.Color(252, 250, 250));
        btnRangeWindow.setText("RANGE");
        btnRangeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRangeWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRangeWindowActionPerformed(evt);
            }
        });
        getContentPane().add(btnRangeWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 180, 50));

        btnStandardDevWindow.setBackground(new java.awt.Color(0, 0, 153));
        btnStandardDevWindow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStandardDevWindow.setForeground(new java.awt.Color(255, 255, 255));
        btnStandardDevWindow.setText("STANDARD DEVIATION");
        btnStandardDevWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStandardDevWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStandardDevWindowActionPerformed(evt);
            }
        });
        getContentPane().add(btnStandardDevWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 260, 60));

        btnQuartileDevWindow.setBackground(new java.awt.Color(0, 51, 153));
        btnQuartileDevWindow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnQuartileDevWindow.setForeground(new java.awt.Color(255, 255, 255));
        btnQuartileDevWindow.setText("QUARTILE DEVIATION");
        btnQuartileDevWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuartileDevWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuartileDevWindowActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuartileDevWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, 250, 50));

        btnCoeffiencientOfVarWindow.setBackground(new java.awt.Color(0, 51, 153));
        btnCoeffiencientOfVarWindow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCoeffiencientOfVarWindow.setForeground(new java.awt.Color(255, 255, 255));
        btnCoeffiencientOfVarWindow.setText("COEFFIENCIENT OF VARIANCE ");
        btnCoeffiencientOfVarWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCoeffiencientOfVarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoeffiencientOfVarWindowActionPerformed(evt);
            }
        });
        getContentPane().add(btnCoeffiencientOfVarWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, 260, 50));

        btnExit.setBackground(new java.awt.Color(255, 0, 51));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 730, 90, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CHOOSE AN OPTION CALCULATE ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 650, 120));

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\java OPerators\\Free-Google-Slides-Math-Background.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1350, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMeanDevWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeanDevWindowActionPerformed
        // TODO add your handling code here:
        MeanDevwindow mdev = new MeanDevwindow();
        mdev.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_btnMeanDevWindowActionPerformed

    private void btnWeighedWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeighedWindowActionPerformed
        // TODO add your handling code here:
        WeighedWindow wei = new WeighedWindow();
        wei.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnWeighedWindowActionPerformed

    private void btnMeanWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeanWindowActionPerformed
        // Mean Window button codes:
        MeanWindow mea = new MeanWindow ();
        mea.setVisible(true);
        this.setVisible(false);
               
        
       
       
    }//GEN-LAST:event_btnMeanWindowActionPerformed

    private void btnModeWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModeWindowActionPerformed
        // Mode Window  button codes :
        ModeWindow mod = new ModeWindow();
        mod.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModeWindowActionPerformed

    private void btnMeadianWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeadianWindowActionPerformed
        // Median Window button codes :
        MeadianWindow med = new MeadianWindow();
        med.setVisible(true);
        this.setVisible(false);
      
    }//GEN-LAST:event_btnMeadianWindowActionPerformed

    private void btnRangeWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRangeWindowActionPerformed
        // Range Window codes :
        RangeWindow ran = new RangeWindow();
        ran.setVisible(true);
        this.setVisible(false);
   
    }//GEN-LAST:event_btnRangeWindowActionPerformed

    private void btnVarianceWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVarianceWindowActionPerformed
        // TODO add your handling code here:
        VarianceWindow var = new VarianceWindow();
        var.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnVarianceWindowActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to close this Application?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnQuartileDevWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuartileDevWindowActionPerformed
        // TODO add your handling code here:
        QuartileDevWindow  Qdw = new QuartileDevWindow();
        Qdw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnQuartileDevWindowActionPerformed

    private void btnStandardDevWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStandardDevWindowActionPerformed
        // TODO add your handling code here:
        StandardDevWindow std = new StandardDevWindow();
        std.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnStandardDevWindowActionPerformed

    private void btnCoeffiencientOfVarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoeffiencientOfVarWindowActionPerformed
        // TODO add your handling code here:
        CoffiencientOfVarWindow cvw = new CoffiencientOfVarWindow();
        cvw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCoeffiencientOfVarWindowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseAnOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseAnOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseAnOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseAnOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseAnOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoeffiencientOfVarWindow;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMeadianWindow;
    private javax.swing.JButton btnMeanDevWindow;
    private javax.swing.JButton btnMeanWindow;
    private javax.swing.JButton btnModeWindow;
    private javax.swing.JButton btnQuartileDevWindow;
    private javax.swing.JButton btnRangeWindow;
    private javax.swing.JButton btnStandardDevWindow;
    private javax.swing.JButton btnVarianceWindow;
    private javax.swing.JButton btnWeighedWindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
